# Generated by Django 5.0.4 on 2024-05-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_product',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
